# Railway Cron Configuration
# This file defines scheduled jobs for Railway

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.cron"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "never"

# Main scraper - runs at 7:00 AM MDT (1:00 PM UTC)
[[cron]]
schedule = "0 13 * * *"
command = "python railway_cron.py"
[cron.env]
CRON_TASK = "main"

# Incremental scraper - runs at 11:00 AM MDT (5:00 PM UTC)  
[[cron]]
schedule = "0 17 * * *"
command = "python railway_cron.py"
[cron.env]
CRON_TASK = "incremental"

# Incremental scraper - runs at 3:00 PM MDT (9:00 PM UTC)
[[cron]]
schedule = "0 21 * * *" 
command = "python railway_cron.py"
[cron.env]
CRON_TASK = "incremental"